# Root directories
root_dir: "/nfs2/harmonization/BIDS/CIBS_BRAIN2_Harmonized/derivatives/"
t1_root_dir: "/nfs2/harmonization/BIDS/CIBS_BRAIN2_Harmonized"
pattern: "sub-*/ses-*/SLANT-TICVv1.2/post/FinalResult/*_T1w_seg.nii.gz"
pattern_run: "sub-*/ses-*/SLANT-TICVv1.2*/post/FinalResult/*_T1w_seg.nii.gz"

# Statistic outputs
roi_volumes_csv: "stats_csv/roi_volumes.csv"
roi_volumes_z_csv: "stats_csv/roi_volumes_zscore.csv"
roi_volumes_ses00_csv: "stats_csv/roi_volumes_ses00.csv"
roi_volumes_ses12_csv: "stats_csv/roi_volumes_ses12.csv"
roi_volumes_ses00_z_csv: "stats_csv/roi_volumes_ses00_zscore.csv"
roi_volumes_ses12_z_csv: "stats_csv/roi_volumes_ses12_zscore.csv"
roi_volumes_delta_pct_csv: "stats_csv/roi_volumes_delta_pct.csv"
roi_volumes_delta_pct_stats_csv: "stats_csv/roi_volumes_delta_pct_stats.csv"

# ROI informations
lut_addr: "labels/slant-ticv.label"
ai_pairs_csv: "labels/slant_ai_pairs.csv"
label_index: "labels/label_index.csv"
